// PrimeGrowth AI — Agent Data
// All 51 agents organized by department for the Command Center dashboard

export type Department = "revenue" | "delivery" | "backoffice" | "meta";
export type AgentStatus = "active" | "idle" | "error" | "future";
export type AgentModel = "opus" | "sonnet";

export interface Agent {
  id: string;
  name: string;
  displayName: string;
  department: Department;
  model: AgentModel;
  status: AgentStatus;
  description: string;
  tags: string[];
  mcpRequired?: string[];
  tasksCompleted: number;
  lastActivity: string;
}

export interface DepartmentInfo {
  label: string;
  color: string;
  bgColor: string;
  borderColor: string;
}

export const DEPARTMENTS: Record<Department, DepartmentInfo> = {
  revenue: {
    label: "Revenue Engine",
    color: "text-amber-400",
    bgColor: "bg-amber-400/8",
    borderColor: "border-amber-400/20",
  },
  delivery: {
    label: "Delivery Engine",
    color: "text-emerald-400",
    bgColor: "bg-emerald-400/8",
    borderColor: "border-emerald-400/20",
  },
  backoffice: {
    label: "Back Office",
    color: "text-blue-400",
    bgColor: "bg-blue-400/8",
    borderColor: "border-blue-400/20",
  },
  meta: {
    label: "Meta Layer",
    color: "text-violet-400",
    bgColor: "bg-violet-400/8",
    borderColor: "border-violet-400/20",
  },
};

export const AGENTS: Agent[] = [
  // ── REVENUE ENGINE ──────────────────────────────────────────────────────
  {
    id: "lead-researcher",
    name: "lead-researcher",
    displayName: "Lead Researcher",
    department: "revenue",
    model: "sonnet",
    status: "idle",
    description: "Finds and qualifies Quebec contractor leads. Enriches with LinkedIn, website, and company data. Scores by ICP fit.",
    tags: ["leads", "prospecting", "research", "lemlist"],
    mcpRequired: [],
    tasksCompleted: 14,
    lastActivity: "2h ago",
  },
  {
    id: "cold-email-architect",
    name: "cold-email-architect",
    displayName: "Cold Email Architect",
    department: "revenue",
    model: "sonnet",
    status: "idle",
    description: "Writes high-converting cold email sequences in French and English. A/B tests subject lines and CTAs.",
    tags: ["email", "outreach", "lemlist", "copywriting"],
    mcpRequired: [],
    tasksCompleted: 22,
    lastActivity: "1d ago",
  },
  {
    id: "linkedin-strategist",
    name: "linkedin-strategist",
    displayName: "LinkedIn Strategist",
    department: "revenue",
    model: "sonnet",
    status: "idle",
    description: "Crafts LinkedIn connection requests, DM sequences, and content posts targeting Quebec contractors.",
    tags: ["linkedin", "social", "outreach"],
    mcpRequired: [],
    tasksCompleted: 8,
    lastActivity: "3d ago",
  },
  {
    id: "meta-ads-manager",
    name: "meta-ads-manager",
    displayName: "Meta Ads Manager",
    department: "revenue",
    model: "sonnet",
    status: "idle",
    description: "Designs Facebook/Instagram ad campaigns. Writes copy, defines audiences, and optimizes for lead cost.",
    tags: ["facebook", "instagram", "ads", "paid"],
    mcpRequired: [],
    tasksCompleted: 5,
    lastActivity: "5d ago",
  },
  {
    id: "instagram-content-engine",
    name: "instagram-content-engine",
    displayName: "Instagram Content Engine",
    department: "revenue",
    model: "sonnet",
    status: "idle",
    description: "Generates full weekly content calendar with hooks, captions, CTAs, and hashtags for contractor audience.",
    tags: ["instagram", "content", "social media"],
    mcpRequired: [],
    tasksCompleted: 3,
    lastActivity: "1w ago",
  },
  {
    id: "social-lead-converter",
    name: "social-lead-converter",
    displayName: "Social Lead Converter",
    department: "revenue",
    model: "sonnet",
    status: "idle",
    description: "Designs GHL + n8n pipeline for comment-to-DM automation. Builds AI qualification flows from Instagram CTAs.",
    tags: ["ghl", "instagram", "automation", "dms"],
    mcpRequired: ["ghl-mcp"],
    tasksCompleted: 2,
    lastActivity: "1w ago",
  },
  {
    id: "video-scriptwriter",
    name: "video-scriptwriter",
    displayName: "Video Scriptwriter",
    department: "revenue",
    model: "sonnet",
    status: "idle",
    description: "Writes short-form video scripts for Reels and HeyGen AI avatar outreach. Optimized for scroll-stopping hooks.",
    tags: ["video", "reels", "heygen", "scripts"],
    mcpRequired: [],
    tasksCompleted: 6,
    lastActivity: "4d ago",
  },
  {
    id: "voice-ai-director",
    name: "voice-ai-director",
    displayName: "Voice AI Director",
    department: "revenue",
    model: "sonnet",
    status: "idle",
    description: "Writes and optimizes ElevenLabs voice scripts for inbound qualification and outbound prospecting calls.",
    tags: ["elevenlabs", "voice", "scripts", "outbound"],
    mcpRequired: [],
    tasksCompleted: 4,
    lastActivity: "3d ago",
  },
  {
    id: "voice-agent-builder",
    name: "voice-agent-builder",
    displayName: "Voice Agent Builder",
    department: "revenue",
    model: "opus",
    status: "idle",
    description: "Builds full ElevenLabs + n8n voice agent pipelines. Handles inbound qualification and outbound prospecting infrastructure.",
    tags: ["elevenlabs", "n8n", "voice", "pipeline"],
    mcpRequired: ["n8n-mcp"],
    tasksCompleted: 1,
    lastActivity: "1w ago",
  },
  {
    id: "call-prep-analyst",
    name: "call-prep-analyst",
    displayName: "Call Prep Analyst",
    department: "revenue",
    model: "sonnet",
    status: "active",
    description: "Prepares comprehensive call briefs from deal files. Surfaces pain points, objections, and recommended questions.",
    tags: ["sales", "discovery", "prep", "calls"],
    mcpRequired: [],
    tasksCompleted: 18,
    lastActivity: "Active",
  },
  {
    id: "proposal-architect",
    name: "proposal-architect",
    displayName: "Proposal Architect",
    department: "revenue",
    model: "opus",
    status: "idle",
    description: "Writes high-converting proposals using client's exact words. Builds ROI calculations and 3-tier pricing structures.",
    tags: ["proposals", "sales", "pricing", "roi"],
    mcpRequired: [],
    tasksCompleted: 7,
    lastActivity: "6h ago",
  },
  {
    id: "gamma-proposal-builder",
    name: "gamma-proposal-builder",
    displayName: "Gamma Proposal Builder",
    department: "revenue",
    model: "opus",
    status: "idle",
    description: "Generates fully designed Gamma slide decks from deal files. Produces live Gamma links ready to present.",
    tags: ["gamma", "proposals", "slides", "presentations"],
    mcpRequired: ["gamma-mcp"],
    tasksCompleted: 2,
    lastActivity: "2d ago",
  },
  {
    id: "deal-closer",
    name: "deal-closer",
    displayName: "Deal Closer",
    department: "revenue",
    model: "opus",
    status: "idle",
    description: "Diagnoses stalled deals and writes objection-handling follow-ups. Recommends channel and timing for each touchpoint.",
    tags: ["sales", "closing", "objections", "follow-up"],
    mcpRequired: [],
    tasksCompleted: 9,
    lastActivity: "1d ago",
  },
  {
    id: "sales-pipeline-manager",
    name: "sales-pipeline-manager",
    displayName: "Sales Pipeline Manager",
    department: "revenue",
    model: "sonnet",
    status: "active",
    description: "Monitors full pipeline daily. Flags overdue follow-ups, drafts messages, and tracks conversion metrics by stage.",
    tags: ["pipeline", "ghl", "crm", "monitoring"],
    mcpRequired: ["ghl-mcp"],
    tasksCompleted: 31,
    lastActivity: "Active",
  },
  {
    id: "call-transcription-analyst",
    name: "call-transcription-analyst",
    displayName: "Call Transcription Analyst",
    department: "revenue",
    model: "sonnet",
    status: "idle",
    description: "Extracts client's exact words from Fireflies transcripts. Writes debriefs and feeds language into proposals automatically.",
    tags: ["fireflies", "transcription", "debrief", "analysis"],
    mcpRequired: [],
    tasksCompleted: 5,
    lastActivity: "3d ago",
  },
  {
    id: "offer-optimizer",
    name: "offer-optimizer",
    displayName: "Offer Optimizer",
    department: "revenue",
    model: "opus",
    status: "idle",
    description: "Analyzes lost deals and objection patterns. Proposes specific changes to offer structure to improve close rate.",
    tags: ["offers", "pricing", "optimization", "cro"],
    mcpRequired: [],
    tasksCompleted: 3,
    lastActivity: "1w ago",
  },
  {
    id: "referral-engine",
    name: "referral-engine",
    displayName: "Referral Engine",
    department: "revenue",
    model: "sonnet",
    status: "idle",
    description: "Designs referral programs and writes ask sequences for closed clients. Tracks referral pipeline in GHL.",
    tags: ["referrals", "growth", "clients"],
    mcpRequired: ["ghl-mcp"],
    tasksCompleted: 0,
    lastActivity: "Not started",
  },

  // ── DELIVERY ENGINE ─────────────────────────────────────────────────────
  {
    id: "n8n-architect",
    name: "n8n-architect",
    displayName: "n8n Architect",
    department: "delivery",
    model: "opus",
    status: "idle",
    description: "Designs complete n8n automation architectures. Maps data flows, identifies edge cases, and writes technical specs before building.",
    tags: ["n8n", "architecture", "automation", "design"],
    mcpRequired: ["n8n-mcp"],
    tasksCompleted: 8,
    lastActivity: "2d ago",
  },
  {
    id: "n8n-builder",
    name: "n8n-builder",
    displayName: "n8n Builder",
    department: "delivery",
    model: "sonnet",
    status: "idle",
    description: "Builds and deploys n8n workflows to Railway. Uses native nodes first, validates JSON, and tests before activation.",
    tags: ["n8n", "railway", "workflows", "build"],
    mcpRequired: ["n8n-mcp"],
    tasksCompleted: 19,
    lastActivity: "1d ago",
  },
  {
    id: "n8n-debugger",
    name: "n8n-debugger",
    displayName: "n8n Debugger",
    department: "delivery",
    model: "opus",
    status: "idle",
    description: "Diagnoses n8n validation loops, expression errors, and webhook failures. Deep analysis with fix recommendations.",
    tags: ["n8n", "debugging", "errors", "validation"],
    mcpRequired: ["n8n-mcp"],
    tasksCompleted: 12,
    lastActivity: "3d ago",
  },
  {
    id: "ghl-manager",
    name: "ghl-manager",
    displayName: "GHL Manager",
    department: "delivery",
    model: "sonnet",
    status: "active",
    description: "Manages GHL contacts, pipelines, sub-accounts, and settings. Handles day-to-day CRM operations across all accounts.",
    tags: ["ghl", "crm", "contacts", "pipelines"],
    mcpRequired: ["ghl-mcp"],
    tasksCompleted: 44,
    lastActivity: "Active",
  },
  {
    id: "ghl-workflow-builder",
    name: "ghl-workflow-builder",
    displayName: "GHL Workflow Builder",
    department: "delivery",
    model: "sonnet",
    status: "idle",
    description: "Builds GHL-native automation workflows for simple triggers and actions that don't require n8n complexity.",
    tags: ["ghl", "workflows", "automation"],
    mcpRequired: ["ghl-mcp"],
    tasksCompleted: 7,
    lastActivity: "4d ago",
  },
  {
    id: "clickup-architect",
    name: "clickup-architect",
    displayName: "ClickUp Architect",
    department: "delivery",
    model: "sonnet",
    status: "idle",
    description: "Designs and optimizes ClickUp workspaces. Builds client project templates, automations, and reporting dashboards.",
    tags: ["clickup", "project management", "operations"],
    mcpRequired: ["clickup-mcp"],
    tasksCompleted: 3,
    lastActivity: "1w ago",
  },
  {
    id: "client-onboarder",
    name: "client-onboarder",
    displayName: "Client Onboarder",
    department: "delivery",
    model: "sonnet",
    status: "idle",
    description: "Runs the full Closed Won workflow: Drive folder, Growth Plan doc, GHL sub-account setup, welcome email.",
    tags: ["onboarding", "clients", "delivery", "setup"],
    mcpRequired: ["ghl-mcp"],
    tasksCompleted: 2,
    lastActivity: "2w ago",
  },
  {
    id: "system-auditor",
    name: "system-auditor",
    displayName: "System Auditor",
    department: "delivery",
    model: "sonnet",
    status: "idle",
    description: "Audits client automation systems monthly. Checks workflow health, identifies bottlenecks, and produces audit reports.",
    tags: ["audit", "quality", "monitoring", "clients"],
    mcpRequired: ["n8n-mcp", "ghl-mcp"],
    tasksCompleted: 4,
    lastActivity: "1w ago",
  },
  {
    id: "documentation-engineer",
    name: "documentation-engineer",
    displayName: "Documentation Engineer",
    department: "delivery",
    model: "sonnet",
    status: "idle",
    description: "Writes technical documentation, SOPs, and client handoff guides. Maintains the GitHub file index.",
    tags: ["documentation", "sops", "github", "writing"],
    mcpRequired: [],
    tasksCompleted: 11,
    lastActivity: "5d ago",
  },
  {
    id: "support-triage",
    name: "support-triage",
    displayName: "Support Triage",
    department: "delivery",
    model: "sonnet",
    status: "idle",
    description: "Triages client support requests. Classifies urgency, routes to correct agent, and drafts initial responses.",
    tags: ["support", "clients", "triage"],
    mcpRequired: [],
    tasksCompleted: 6,
    lastActivity: "3d ago",
  },
  {
    id: "client-success",
    name: "client-success",
    displayName: "Client Success",
    department: "delivery",
    model: "sonnet",
    status: "idle",
    description: "Manages client health scores, tracks ROI delivery, and identifies upsell opportunities at 30/60/90 day marks.",
    tags: ["clients", "retention", "upsell", "health"],
    mcpRequired: ["ghl-mcp"],
    tasksCompleted: 1,
    lastActivity: "2w ago",
  },

  // ── BACK OFFICE ─────────────────────────────────────────────────────────
  {
    id: "financial-analyst",
    name: "financial-analyst",
    displayName: "Financial Analyst",
    department: "backoffice",
    model: "sonnet",
    status: "idle",
    description: "Tracks revenue, margins, and expenses. Produces weekly P&L summaries and flags financial anomalies.",
    tags: ["finance", "revenue", "margins", "reporting"],
    mcpRequired: [],
    tasksCompleted: 8,
    lastActivity: "1w ago",
  },
  {
    id: "invoice-manager",
    name: "invoice-manager",
    displayName: "Invoice Manager",
    department: "backoffice",
    model: "sonnet",
    status: "idle",
    description: "Creates and tracks invoices. Sends payment reminders and flags overdue accounts.",
    tags: ["invoicing", "payments", "billing"],
    mcpRequired: [],
    tasksCompleted: 5,
    lastActivity: "4d ago",
  },
  {
    id: "quickbooks-controller",
    name: "quickbooks-controller",
    displayName: "QuickBooks Controller",
    department: "backoffice",
    model: "sonnet",
    status: "future",
    description: "FUTURE STATE — Will manage QuickBooks Online: categorize expenses, reconcile accounts, and generate tax reports.",
    tags: ["quickbooks", "accounting", "taxes"],
    mcpRequired: ["quickbooks-mcp"],
    tasksCompleted: 0,
    lastActivity: "Not activated",
  },
  {
    id: "contract-reviewer",
    name: "contract-reviewer",
    displayName: "Contract Reviewer",
    department: "backoffice",
    model: "opus",
    status: "idle",
    description: "Reviews service agreements and client contracts. Flags risky clauses and suggests protective language.",
    tags: ["contracts", "legal", "review"],
    mcpRequired: [],
    tasksCompleted: 3,
    lastActivity: "2w ago",
  },
  {
    id: "inbox-triage",
    name: "inbox-triage",
    displayName: "Inbox Triage",
    department: "backoffice",
    model: "sonnet",
    status: "idle",
    description: "Categorizes emails by urgency and type. Drafts responses for routine inquiries and flags items requiring David's attention.",
    tags: ["email", "inbox", "triage"],
    mcpRequired: [],
    tasksCompleted: 27,
    lastActivity: "2h ago",
  },
  {
    id: "calendar-optimizer",
    name: "calendar-optimizer",
    displayName: "Calendar Optimizer",
    department: "backoffice",
    model: "sonnet",
    status: "idle",
    description: "Manages scheduling, blocks deep work time, and ensures call prep is scheduled before every prospect meeting.",
    tags: ["calendar", "scheduling", "time management"],
    mcpRequired: [],
    tasksCompleted: 15,
    lastActivity: "1d ago",
  },
  {
    id: "vendor-manager",
    name: "vendor-manager",
    displayName: "Vendor Manager",
    department: "backoffice",
    model: "sonnet",
    status: "idle",
    description: "Tracks all SaaS subscriptions, costs, and renewal dates. Flags unused tools and optimizes the tech stack spend.",
    tags: ["vendors", "saas", "costs", "subscriptions"],
    mcpRequired: [],
    tasksCompleted: 2,
    lastActivity: "1w ago",
  },
  {
    id: "slack-coordinator",
    name: "slack-coordinator",
    displayName: "Slack Coordinator",
    department: "backoffice",
    model: "sonnet",
    status: "future",
    description: "FUTURE STATE — Will manage Slack client communications, route messages, and send automated project updates.",
    tags: ["slack", "communications", "clients"],
    mcpRequired: ["slack-mcp"],
    tasksCompleted: 0,
    lastActivity: "Not activated",
  },
  {
    id: "competitor-monitor",
    name: "competitor-monitor",
    displayName: "Competitor Monitor",
    department: "backoffice",
    model: "sonnet",
    status: "idle",
    description: "Tracks competitor pricing, offers, and positioning in the Quebec automation consulting market.",
    tags: ["competitive intelligence", "market research"],
    mcpRequired: [],
    tasksCompleted: 1,
    lastActivity: "1w ago",
  },

  // ── META LAYER ───────────────────────────────────────────────────────────
  {
    id: "orchestrator",
    name: "orchestrator",
    displayName: "Orchestrator",
    department: "meta",
    model: "opus",
    status: "active",
    description: "The COO. Runs daily briefings, coordinates all agents, and directs David's attention to highest-leverage actions.",
    tags: ["orchestration", "briefing", "coordination"],
    mcpRequired: [],
    tasksCompleted: 47,
    lastActivity: "Active",
  },
  {
    id: "memory-keeper",
    name: "memory-keeper",
    displayName: "Memory Keeper",
    department: "meta",
    model: "sonnet",
    status: "idle",
    description: "Commits session state to Hindsight and GitHub. Maintains the shared knowledge base and session summaries.",
    tags: ["memory", "hindsight", "github", "context"],
    mcpRequired: [],
    tasksCompleted: 62,
    lastActivity: "4h ago",
  },
  {
    id: "github-archivist",
    name: "github-archivist",
    displayName: "GitHub Archivist",
    department: "meta",
    model: "sonnet",
    status: "idle",
    description: "Manages repo structure, file index, and commit hygiene. Ensures all work is properly documented and versioned.",
    tags: ["github", "documentation", "versioning"],
    mcpRequired: [],
    tasksCompleted: 38,
    lastActivity: "6h ago",
  },
  {
    id: "prompt-optimizer",
    name: "prompt-optimizer",
    displayName: "Prompt Optimizer",
    department: "meta",
    model: "opus",
    status: "idle",
    description: "Analyzes agent outputs and improves system prompts based on real outcomes. The flywheel that makes all agents better over time.",
    tags: ["optimization", "prompts", "improvement", "meta"],
    mcpRequired: [],
    tasksCompleted: 5,
    lastActivity: "3d ago",
  },
  {
    id: "self-improvement-loop",
    name: "self-improvement-loop",
    displayName: "Self-Improvement Loop",
    department: "meta",
    model: "opus",
    status: "idle",
    description: "Weekly cron agent. Scans all session outputs, identifies manual tasks, and proposes new agents to automate them.",
    tags: ["automation", "improvement", "weekly", "cron"],
    mcpRequired: [],
    tasksCompleted: 2,
    lastActivity: "1w ago",
  },
  {
    id: "agent-capture-system",
    name: "agent-capture-system",
    displayName: "Agent Capture System",
    department: "meta",
    model: "sonnet",
    status: "idle",
    description: "Watches terminal activity for repeated tasks. Automatically drafts new agent files when patterns are detected.",
    tags: ["automation", "capture", "agents", "patterns"],
    mcpRequired: [],
    tasksCompleted: 3,
    lastActivity: "2d ago",
  },
  {
    id: "agent-installer",
    name: "agent-installer",
    displayName: "Agent Installer",
    department: "meta",
    model: "sonnet",
    status: "idle",
    description: "Finds, evaluates, and installs new Claude Code agents from the community. Keeps the agent library current.",
    tags: ["agents", "installation", "community"],
    mcpRequired: [],
    tasksCompleted: 4,
    lastActivity: "1w ago",
  },
  {
    id: "infrastructure-monitor",
    name: "infrastructure-monitor",
    displayName: "Infrastructure Monitor",
    department: "meta",
    model: "sonnet",
    status: "active",
    description: "Monitors Railway n8n, GHL sub-accounts, and all service health. Alerts on failures and latency spikes.",
    tags: ["monitoring", "railway", "n8n", "infrastructure"],
    mcpRequired: ["n8n-mcp"],
    tasksCompleted: 89,
    lastActivity: "Active",
  },
  {
    id: "cron-runner",
    name: "cron-runner",
    displayName: "Cron Runner",
    department: "meta",
    model: "sonnet",
    status: "idle",
    description: "Headless agent for scheduled overnight tasks: financial reviews, pipeline checks, vendor audits, and health checks.",
    tags: ["cron", "scheduled", "overnight", "automation"],
    mcpRequired: [],
    tasksCompleted: 12,
    lastActivity: "Last night",
  },
  {
    id: "multi-agent-coordinator",
    name: "multi-agent-coordinator",
    displayName: "Multi-Agent Coordinator",
    department: "meta",
    model: "opus",
    status: "idle",
    description: "Coordinates concurrent agents with shared state, synchronization points, and distributed failure handling. Sourced from VoltAgent community library.",
    tags: ["coordination", "concurrent", "fault-tolerance", "community"],
    mcpRequired: [],
    tasksCompleted: 0,
    lastActivity: "Never",
  },
  {
    id: "workflow-orchestrator",
    name: "workflow-orchestrator",
    displayName: "Workflow Orchestrator",
    department: "meta",
    model: "opus",
    status: "idle",
    description: "Designs and executes complex business process workflows with state machines, error handling, and transaction management. Sourced from VoltAgent community library.",
    tags: ["workflow", "state-machine", "transactions", "community"],
    mcpRequired: [],
    tasksCompleted: 0,
    lastActivity: "Never",
  },
  // ── REVENUE ENGINE (new) ─────────────────────────────────────────────────
  {
    id: "lemlist-manager",
    name: "lemlist-manager",
    displayName: "Lemlist Manager",
    department: "revenue",
    model: "opus",
    status: "idle",
    description: "Manages all lemlist outbound campaigns: create sequences, import leads, audit performance, rewrite copy. Requires lemlist MCP server.",
    tags: ["lemlist", "campaigns", "outbound", "cold-email", "mcp"],
    mcpRequired: ["lemlist"],
    tasksCompleted: 0,
    lastActivity: "Not connected",
  },
  // ── META LAYER (new) ─────────────────────────────────────────────────────
  {
    id: "dispatcher",
    name: "dispatcher",
    displayName: "Dispatcher",
    department: "meta",
    model: "opus",
    status: "active",
    description: "Master sequential task router. Accepts any plain-language request, builds a chain of specialist agents, passes shared context forward, and returns one synthesized output.",
    tags: ["orchestration", "routing", "sequential", "multi-agent", "primary"],
    mcpRequired: [],
    tasksCompleted: 0,
    lastActivity: "Ready",
  },
  {
    id: "content-adapter",
    name: "content-adapter",
    displayName: "Content Adapter",
    department: "meta",
    model: "sonnet",
    status: "idle",
    description: "Repurposes content across formats: turns a LinkedIn post into an email, a video script into a blog, a proposal into a case study.",
    tags: ["content", "repurpose", "cross-format", "adaptation"],
    mcpRequired: [],
    tasksCompleted: 0,
    lastActivity: "Never",
  },
];

// ── Helpers ──────────────────────────────────────────────────────────────────

export function getAgentsByDepartment(dept: Department): Agent[] {
  return AGENTS.filter((a) => a.department === dept);
}

export function getActiveAgents(): Agent[] {
  return AGENTS.filter((a) => a.status === "active");
}

export function getTotalTasksCompleted(): number {
  return AGENTS.reduce((sum, a) => sum + a.tasksCompleted, 0);
}

// ── Slash Commands ────────────────────────────────────────────────────────────

export interface SlashCommand {
  command: string;
  description: string;
}

export const SLASH_COMMANDS: SlashCommand[] = [
  { command: "/daily-briefing", description: "Run full morning briefing" },
  { command: "/new-deal", description: "Create new deal file from discovery" },
  { command: "/post-call", description: "Debrief a completed call" },
  { command: "/build-system", description: "Start a client automation build" },
  { command: "/weekly-review", description: "Run weekly business review" },
  { command: "/commit-memory", description: "Save session state to memory" },
];
